[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
hello_world = "5UXHK6Gcgxsfb8FYVB9Y46SPccwH16fP1gzvUXjeUkG"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
