[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
escrow = "7JhnKE64RxpA87SeqUU1PDGvrM5qTxxsecUaLn5tYsg"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "../Rust-prereq-task-2/src/turbine-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
